name: Lane Designs
favicon: null
layout_spectrum: 0.6331794196739793
typography_spectrum: 0.1531396913342178
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.45274347509257495
  lightness: 0.7464050233829767
  saturation: 0.0738042276352644
  rhythmicContrast: 0.6002697900403291
purpose: []
